version: "3.9"

services:
  client:
    build: ./rsyslog
    hostname: client
    privileged: true
    volumes:
      - ./rsyslog/client.conf:/tmp/rsyslog.conf
      - ./.ssl:/tmp/.ssl
    links:
      - server

  server:
    build: ./rsyslog
    hostname: server
    volumes:
      - ./rsyslog/server.conf:/tmp/rsyslog.conf
      - ./.ssl:/tmp/.ssl
